# this is needed to talk to the oracle database in OCI, it's not to be shared !
# using the OCI CLI you can get the walled
# oci db autonomous-database generate-wallet \
#  --autonomous-database-id <autonomous-database-ocid> \
#  --file wallet.zip \
#  --password '<wallet-password>'
# connection name from the tneames.ora file e.g. telemetry_high
timeseriesdb.jdbc.connectionname=<connecton name>
# relative or absolute path to the wallet file directotry
# e.g. .configsecure/timeseriesdb
timeseriesdb.jdbc.walletpath=<path to wallet directory>
timeseriesdb.jdbc.username=<username>
timeseriesdb.jdbc.password=<password>
# this is optional, will default to jdbc:oracle:thin:
#timeseriesdb.jdbc.driver=<password>