# this is needed to talk to the oracle database in OCI, it's not to be shared !
datasources.timeseries.dialect=ORACLE
datasources.timeseries.ocid=<db ocid (in region specified by chosen config file entry)>
datasources.timeseries.walletPassword=<A password for the downloaded wallet>
datasources.timeseries.username=<The user name of the ingest user>
datasources.timeseries.password=<The password of the ingest user>