datasources.default.url=tcps:adb.${iotdatacache.ociregion}.oraclecloud.com:1521/${iotdatacache.connectionname}.adb.oraclecloud.com
datasources.default.username=
datasources.default.password=

iotdatacache.aq.uselistener=false
iotdatacache.aq.usereader=true
iotdatacache.aq.readtimeout=10
iotdatacache.aq.batchsize=10

iotdatacache.jdbc.doconnectiontestread.enabled=true
iotdatacache.jdbc.doconnectiontestread.order=0

iotdatacache.aq.reader.enabled=true
iotdatacache.aq.reader.order=10
iotdatacache.aq.listener.enabled=false
iotdatacache.aq.listener.order=20

normalizeddata.handler.textoutput.order=10

#oci.auth.type=InstancePrinciple
#oci.auth.type=ConfigFile
#oci.auth.config.section=DEFAULT

oci.dbtoken.scope=urn:oracle:db::id::${oci.dbtoken.compartment}