datasources.default.url=tcps:adb.${iotdatacache.ociregion}.oraclecloud.com:1521/${iotdatacache.connectionname}.adb.oraclecloud.com
datasources.default.username=
datasources.default.password=


iotdatacache.jdbc.doconnectiontestread.enabled=true
iotdatacache.jdbc.doconnectiontestread.order=0

# enable readers / listeners as required
#iotdatacache.aq.batchreader.enabled=true
#iotdatacache.aq.batchreader.order=10
#iotdatacache.aq.batchreader.readtimeout=10
#iotdatacache.aq.batchreader.batchsize=10
#iotdatacache.aq.individualreader.enabled=false
#iotdatacache.aq.individualreader.order=15
#iotdatacache.aq.individualreader.readtimeout=10
#iotdatacache.aq.individualreader.batchsize=10
iotdatacache.aq.listener.enabled=false
iotdatacache.aq.listener.order=20

#normalizeddata.handler.textoutput.order=10
#normalizeddata.handler.textoutput.enabled=false
#normalizeddata.handler.textoutput.passthrough=true
#normalizeddata.handler.contentpathfilter.enabled=true
#normalizeddata.handler.contentpathfilter.order=20
# the string to look for, or a regexp to be found within the content path
#normalizeddata.handler.contentpathfilter.regexp=Solar
# is characted matching case in senstive (default false)
#normalizeddata.handler.contentpathfilter.caseinsensitive=false
#Are we looking for the rexexp (default FOUND) or looking for it not to be there (NOT_FOUND)
#normalizeddata.handler.contentpathfilter.findoutcome=FOUND

#oci.auth.type=InstancePrinciple
#oci.auth.type=ConfigFile
#oci.auth.config.section=DEFAULT

oci.dbtoken.scope=urn:oracle:db::id::${oci.dbtoken.compartment}