datasources.default.url=tcps:adb.${iotdatacache.ociregion}.oraclecloud.com:1521/${iotdatacache.connectionname}.adb.oraclecloud.com
datasources.default.username=
datasources.default.password=

iotdatacache.aqname=normalized_data
  
oci.authtype=InstanceProvider

oci.dbtoken.scope=urn:oracle:db::id::${oci.dbtoken.compartment}