# These set the core operating modes. Note that in addition to these properties you also need to set 
# the relevant properties for the function (e.g. home assistant credentials to be able to read from it and mqtt
# credentials to be able to upload to IoT
#
# Defaults are to get input from HOME_ASSISTANT and send output to MQTT
#
# this controls where data comes from - retrieved live from Home Assistant or uploaded from a recording
# options are HOME_ASSISTANT, REPLAY, NONE - see the OperatingModeInput class
# default is HOME_ASSISTANT
operatingmodes.inputmode=HOME_ASSISTANT
# this controls where data is sent to - written to a file for later replay or uploaded using MQTT to the IoT service
# options are RECORDER, MQTT, NONE - see the OperatingModeOutput class
# default is MQTT
operatingmodes.outputmode=MQTT
# the following combinations will do something useful
# HOME_ASSISTANT to MQTT
# HOME_ASSISTANT to RECORDER
# REPLAY to MQTT
# HOME_ASSISTANT to NONE will just output the live events, potentially useful for debugging data capture
# REPLAY to NONE will just replay the recorded events, might be useful for debugging the replay process
# the following are useful for testing the dependenc injection process only on the output side of things
# NONE to any of RECORDER, MQTT, NONE
# The following probably will not do anything viable, or it might just transfer input data to the output (unclear)
# REPLAY to RECORDER 