# replaced with operatingmodes.outputmode record.enabled=false
record.output.file=recordeddata.txt
record.output.directory=savedata
record.output.prefixwithdtg=true
record.duration=4h
#record.startat=2026-09-28T00-00-01.000000Z
