record.enabled=false
record.output.file=recordeddata.txt
record.output.directory=savedata
record.output.prefixwithdtg=true
record.duration=10s

gateway.config.enabled=false
gateway.stats.enabled=false